### PR TITLE
Equalizer beta

### PR DESCRIPTION
**Pull request by jessicabarbalho**
I developed an equalizer, it's not all okay, but I want you see to give me some feedback :)

In the menu of the player I added a button `Equalizer` And there you can see a list of radio buttons with presets equalizations, you click and works, if you change the music the settings will be keeped.

The radio buttons are not okay yet, but I want solve this and put a `ScrollView` in this activity too.

xD

### CODE REVIEW

**Comment by jessicabarbalho** [comment]
I think here we have a great equalizer with preset list and custom options :)
For sure the desgin can be improved, you can give some feedback and we can work on it :D

**Comment by MarcinGil** [comment]
Hi Jessica, sorry for not getting to you for so long. I'm currently overloaded with some project and have very little time.

**Comment by jessicabarbalho** [comment]
I'm so glad, any problem we can contact me :) I wish continue working on it.

**Comment by MarcinGil** [comment]
On Thursday 19 of July 2012 04:09:39 you wrote:

> I'm so glad, any problem we can contact me :) I wish continue working on it.

Please do so. I'm thinking that maybe the Equalizer button should not only 
display "Equalizer" but maybe also show which preset is currently on.

**Pull request merged**
