### PR TITLE
Equalizer on ICS/JB

### PR DESCRIPTION
**Pull request by dargad**
I think I have a solution for the Equalizer problem ([issue #24](https://github.com/telecapoland/jamendo-android/issues/24)).

The root cause was the fact that most probably on ICS+ versions Equalizer is bound to the lifetime of a MediaPlayer. As a result every time after MediaPlayer is released Equalizer needs to be released as well.

This caused some architectural changes - a global equalizer object can no longer be used (since it was valid only as long as the same song was playing). 

There were two special cases to be handled (when the global equalizer is unavailable):
- the song is stopped (no MediaPlayer object) and we want to manipulate the equalizer
- we open the equalizer during one song, it finishes and the next one is played - then we manipulate the equalizer
  Those cases needed to be covered by some kind of settings serialization and passing to the next Equalizer. Luckily, the Equalizer.Settings class have all what was needed for that purpose.

The global Equalizer object is used only when available (this is checked by the JamendoApplication.isEqualizerRunning method) to apply the settings in runtime. All other situations (no media playback) are covered using the Settings object instance passed to the newly created equalizer.

As a side effect I have implemented an Equalizer settings persistence mechanism to store settings between app launches.

Additionally I have found a typo in layout-mdpi/player.xml - pressing the Equalizer button was triggering 'Add to playlist' action.

I have added an additional permission (android.permission.MODIFY_AUDIO_SETTINGS) to the manifest. This was necessary to occasionally create a global Equalizer object to obtain some common settings (presets, number of bands and their level range) when the JamendoApplication.mEqualizer was not available.

I have verified this solution on Nexus S (JB), Sony Xperia P (ICS) and Samsung Galaxy Gio (GB). Seems to be working correctly.

### CODE REVIEW

**Comment by MarcinGil** [comment]
Cool, let me grok on this a bit (especially the change of minSDK value).

**Comment by dargad** [comment]
Sure. 

The motivation behind altering minSDKVersion was the fact thath without modification the app is allowed to be installed on API level < 9 and then crashes with (even without my changes - on current master):

```
09-10 18:41:03.286: E/AndroidRuntime(322): java.lang.NoClassDefFoundError: android.media.audiofx.Equalizer
09-10 18:41:03.286: E/AndroidRuntime(322):  at com.teleca.jamendo.media.PlayerEngineImpl.play(PlayerEngineImpl.java:221)
09-10 18:41:03.286: E/AndroidRuntime(322):  at com.teleca.jamendo.media.PlayerEngineImpl$3.onPrepared(PlayerEngineImpl.java:327)
09-10 18:41:03.286: E/AndroidRuntime(322):  at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:1234)
09-10 18:41:03.286: E/AndroidRuntime(322):  at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 18:41:03.286: E/AndroidRuntime(322):  at android.os.Looper.loop(Looper.java:123)
09-10 18:41:03.286: E/AndroidRuntime(322):  at android.app.ActivityThread.main(ActivityThread.java:4627)
09-10 18:41:03.286: E/AndroidRuntime(322):  at java.lang.reflect.Method.invokeNative(Native Method)
09-10 18:41:03.286: E/AndroidRuntime(322):  at java.lang.reflect.Method.invoke(Method.java:521)
09-10 18:41:03.286: E/AndroidRuntime(322):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
09-10 18:41:03.286: E/AndroidRuntime(322):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
09-10 18:41:03.286: E/AndroidRuntime(322):  at dalvik.system.NativeStart.main(Native Method)
```

I belive that if the API Level 4 compatibility needs to be supported the Equalizer should have been wrapped around with some reflection tricks to be actually used only on GB+ releases.

**Comment by dargad** [comment]
If you consider remaining compatible with API level 4 important, please let me know. I can gladly provide a patch that wraps Equalizer API with either reflection or a wrapper class (as described [here](http://android-developers.blogspot.com/2009/04/backward-compatibility-for-android.html)) to be safely used on pre-GB software.

Btw. I have noticed that the equalizer presets differ across devices, so I've commited a [change](https://github.com/isdes/jamendo-android/commit/52effeed2d1876be8b15156ada9baf9403f9ed91) that fetches preset names dynamically.

**Comment by MarcinGil** [comment]
So here's my opinion: since we CAN have two (or more) APKs for the same app on the market - we can simply stop evolving current version (remove Equalizer, make it 3-8 API level compatible) and just fix bugs for it. And start a new version that is 9-up compatible. Comments?

**Comment by MarcinGil** [comment]
By the way, we already have a version that is 3-up compatible and not maintained (0.9) that is for OLD devices. It doesn't even have current fixes (and possibly doesn't work at all since Jamendo changed APIs). Reconsidering above -- we can just up the API level. :)

Considering [current API distribution](http://developer.android.com/about/dashboards/index.html) support for Froyo might be left behind.. I think to create the <9 branch, remove equalizer from there, put to market and then up min SDK required.

**Comment by dargad** [comment]
Sounds good to me :)

**Comment by MarcinGil** [comment]
Created low-api-support branch to keep < API-9 support. Will modify max SDK level and remove Equalizer from there.

**Pull request merged**
